# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Email'),
        ),
    ]
