# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_specialcargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SpecialCargo',
            field=models.BooleanField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='Спецгруз?'),
        ),
    ]
