# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20201211_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('volumetricHeight', models.PositiveIntegerField(verbose_name='Высота')),
                ('volumetricWidth', models.PositiveIntegerField(verbose_name='Ширина')),
                ('volumetricLength', models.PositiveIntegerField(verbose_name='Длина')),
                ('cost', models.FloatField(verbose_name='Оценочная стоимость')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('specialCargo', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='checkout.Order')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Место',
            },
        ),
    ]
