# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-12 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201212_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='SpecialCargo',
        ),
    ]
