# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20201212_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
    ]
