from .index import *
from .prices import *
from .stock import *
from .add import *
from .edit import EditView
from .delete import delete
from .list import items
from .search import search
from .departaments import city,departaments
from .gallery import ordering
from .autocomplete import autocomplete,order_autocomplete
from .database import change_database