# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-16 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200916_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
    ]
