# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-16 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.BrandDescription'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.CategoryDescription'),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.CityDescription'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.PageDescription'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.ProductDescription'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.TagDescription'),
        ),
    ]
