# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-16 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200916_1136'),
        ('catalog', '0007_auto_20200916_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branddescription',
            unique_together=set([('language', 'meta_description'), ('language', 'name'), ('language', 'title')]),
        ),
    ]
