# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-16 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200916_1136'),
        ('catalog', '0008_auto_20200916_1707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorydescription',
            unique_together=set([('language', 'title'), ('language', 'name'), ('language', 'meta_description')]),
        ),
        migrations.AlterUniqueTogether(
            name='citydescription',
            unique_together=set([('language', 'title'), ('language', 'name'), ('language', 'meta_description')]),
        ),
        migrations.AlterUniqueTogether(
            name='pagedescription',
            unique_together=set([('language', 'title'), ('language', 'name'), ('language', 'meta_description')]),
        ),
        migrations.AlterUniqueTogether(
            name='productdescription',
            unique_together=set([('language', 'title'), ('language', 'name'), ('language', 'meta_description')]),
        ),
        migrations.AlterUniqueTogether(
            name='tagdescription',
            unique_together=set([('language', 'title'), ('language', 'name'), ('language', 'meta_description')]),
        ),
    ]
