# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-29 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200923_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.PositiveIntegerField(choices=[(1, 'Розничная'), (2, 'Узнать стоимость')], default=1, null=True, verbose_name='Склад'),
        ),
    ]
