# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20201011_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
