# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20201018_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='counter',
            field=models.CharField(default='шт.', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.PositiveIntegerField(choices=[(1, 'CKL'), (2, 'Уточняйте цену')], default=1, null=True, verbose_name='Склад'),
        ),
    ]
