# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20201027_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'UAH'), (1, 'EUR'), (2, 'USD')], default=0)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
    ]
