# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-27 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.FloatField(),
        ),
    ]
