# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20201027_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'UAH'), (1, 'EUR'), (2, 'USD')], default=0, unique=True),
        ),
    ]
