# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20201028_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_opt_price',
            field=models.FloatField(default=0, verbose_name='Биг-оптовая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(default=0, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.PositiveIntegerField(choices=[(1, 'CKL'), (2, 'Уточняйте цену')], default=1, null=True, verbose_name='Склад'),
        ),
    ]
