# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_remove_page_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='view',
            field=models.CharField(default='Page', max_length=20),
        ),
    ]
