# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_product_is_top'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_available', '-last_modified', '-is_top'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.PositiveIntegerField(choices=[(1, 'CKL'), (2, 'Уточняйте цену')], default=1, null=True, verbose_name='Склад'),
        ),
    ]
