# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_auto_20201226_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NoLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='load_merchant',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='load_rozetka',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='merchant_from',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='merchant_to',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='rozetka_from',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='rozetka_to',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.PositiveIntegerField(choices=[(1, 'Игротека'), (2, 'Велис'), (3, 'Тигрес')], default=1, null=True, verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='noload',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noload', to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='load',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='catalog.Product'),
        ),
    ]
