# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-25 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_auto_20210116_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Rozetka.ua'), (2, 'Google.com'), (3, 'Hotline.ua')], default=1)),
                ('load', models.BooleanField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export', to='catalog.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='load',
            name='product',
        ),
        migrations.RemoveField(
            model_name='noload',
            name='product',
        ),
        migrations.AddField(
            model_name='productdescription',
            name='rozetka',
            field=redactor.fields.RedactorField(null=True, verbose_name='Описание Rozetka.ua'),
        ),
        migrations.DeleteModel(
            name='Load',
        ),
        migrations.DeleteModel(
            name='NoLoad',
        ),
    ]
