# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_auto_20210125_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='rozetka_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя Rozetka.ua'),
        ),
    ]
