# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_productdescription_rozetka_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ManyToManyField(related_name='attributes', to='catalog.Category'),
        ),
    ]
