# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-09 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_auto_20210209_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='load_merchant',
        ),
        migrations.RemoveField(
            model_name='category',
            name='load_rozetka',
        ),
        migrations.RemoveField(
            model_name='category',
            name='merchant_from',
        ),
        migrations.RemoveField(
            model_name='category',
            name='merchant_to',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rozetka_from',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rozetka_to',
        ),
    ]
