# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-13 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('active', models.BooleanField(default=0, verbose_name='Активна')),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255, null=True, unique=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Полезные статьи',
                'verbose_name_plural': 'Полезные статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticleDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', redactor.fields.RedactorField(null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=255, null=True)),
                ('meta_keywords', models.CharField(max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Language')),
            ],
            options={
                'db_table': 'article_description',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.ManyToManyField(to='blog.ArticleDescription'),
        ),
    ]
