# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledescription',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
