# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-16 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200916_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='blog.ArticleDescription'),
        ),
    ]
