# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-16 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200916_1136'),
        ('blog', '0003_auto_20200916_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articledescription',
            unique_together=set([('language', 'title'), ('language', 'name'), ('language', 'meta_description')]),
        ),
    ]
