# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-26 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200923_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articledescription',
            unique_together=set([]),
        ),
    ]
