# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-26 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200929_1439'),
        ('blog', '0006_auto_20201026_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articledescription',
            unique_together=set([('language', 'name'), ('language', 'title'), ('language', 'meta_description')]),
        ),
    ]
