# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-26 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201026_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articledescription',
            unique_together=set([]),
        ),
    ]
