# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-26 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200929_1439'),
        ('blog', '0010_auto_20201026_1253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articledescription',
            unique_together=set([('language', 'name')]),
        ),
    ]
