# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='lang/')),
                ('name', models.CharField(max_length=20, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('ISOcode', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Percents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255, verbose_name='Сайт')),
                ('before_twenty', models.FloatField(default=3, verbose_name='до 20')),
                ('twenty_thirty', models.FloatField(default=2, verbose_name='20-30')),
                ('thirty_fifty', models.FloatField(default=1.7, verbose_name='30-50')),
                ('fifty_hundred', models.FloatField(default=1.5, verbose_name='50-100')),
                ('hundred_threehundred', models.FloatField(default=1.4, verbose_name='100-300')),
                ('threehundred_fivehundred', models.FloatField(default=1.25, verbose_name='300-500')),
                ('fivehundred_onethousand', models.FloatField(default=1.2, verbose_name='500-1000')),
                ('onethousand_twothousand', models.FloatField(default=1.15, verbose_name='1000-2000')),
                ('default', models.FloatField(default=1.1, verbose_name='более 2к')),
            ],
            options={
                'verbose_name': 'Наценка',
                'verbose_name_plural': 'Наценка',
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номер телефона',
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=255, unique=True)),
                ('new_path', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автар')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', redactor.fields.RedactorField(verbose_name='Текст отзыва')),
                ('active', models.BooleanField(default=0, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='shop.Review')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, verbose_name='Текст')),
                ('mobile', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'robots',
                'verbose_name_plural': 'robots',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Сессии')),
                ('csrftoken', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSRF-token')),
                ('percent_toys', models.FloatField(blank=True, null=True, verbose_name='Процентная скидка')),
                ('percent_beles', models.FloatField(blank=True, null=True, verbose_name='Процентная скидка')),
                ('attention_message', models.CharField(max_length=255, null=True, verbose_name='Уведомление')),
                ('load_beles_categories', models.BooleanField(default=False, verbose_name='Загрузить категории "велис"?')),
                ('uncheck_velis', models.BooleanField(default=False, verbose_name='Обиновить весь Велис')),
                ('sitemap_cache', models.DateTimeField(null=True)),
                ('sitemaphtml_cache', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True, verbose_name='domain name')),
                ('name', models.CharField(max_length=50, verbose_name='display name')),
                ('host', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'db_table': 'django_site',
                'ordering': ('domain',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='URL')),
                ('image', models.ImageField(max_length=255, upload_to='data/slider/', verbose_name='Изображение')),
                ('position', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='phones',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='shop.Settings'),
        ),
    ]
