# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='api_key',
            field=models.CharField(max_length=255, null=True, verbose_name='API_KEY novaposhta.ua'),
        ),
        migrations.AddField(
            model_name='settings',
            name='contactsRef',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='senderRef',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
