# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-29 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200916_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-id']},
        ),
    ]
