# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200929_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
