# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_settings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='google_analytics',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='google_tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='google_verification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='settings',
            name='wotermark',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
    ]
