# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-03 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201125_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='csrftoken',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='load_beles_categories',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='percent_beles',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='percent_toys',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sitemaphtml_cache',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='uncheck_velis',
        ),
        migrations.AlterField(
            model_name='settings',
            name='attention_message',
            field=models.CharField(max_length=255, null=True, verbose_name='Важное уведомление в шапке сайта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='novaposhta.ua телефон'),
        ),
    ]
