# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-21 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201203_1223'),
        ('shop', '0006_connection'),
    ]

    operations = [
    ]
