# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-24 16:51
from __future__ import unicode_literals

from django.db import migrations
import shop.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201221_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='setting',
        ),
        migrations.AddField(
            model_name='settings',
            name='emails',
            field=shop.fields.JSONField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='phones',
            field=shop.fields.JSONField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
    ]
