# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201224_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон novaposhta.ua'),
        ),
    ]
