# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-09 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201225_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.PositiveIntegerField(default=1)),
                ('js', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
