# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta',
            old_name='text',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='meta',
            old_name='type',
            new_name='model',
        ),
        migrations.AddField(
            model_name='meta',
            name='meta_keywords',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='meta',
            unique_together=set([('language', 'model')]),
        ),
    ]
