# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-14 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200914_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='model',
            field=models.PositiveIntegerField(choices=[(1, 'Product'), (2, 'Category'), (3, 'Brand'), (4, 'Tag'), (5, 'Page'), (6, 'Article'), (7, 'City')]),
        ),
    ]
