# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200916_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API_KEY novaposhta.ua')),
                ('senderRef', models.CharField(max_length=255, null=True)),
                ('contactsRef', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
