# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200916_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tigresgallery',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='products/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
