# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201026_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.PositiveIntegerField(choices=[(1, 'Google Merchant'), (2, 'Синхронизация цен'), (3, 'Facebook Merchant'), (4, 'Пересчет цен')]),
        ),
    ]
