# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201104_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='percent',
            name='additional',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
