# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_percent_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.PositiveIntegerField(choices=[(1, 'Google Merchant'), (2, 'Синхронизация цен'), (3, 'Facebook Merchant'), (4, 'Пересчет цен'), (5, 'Синх производителя')]),
        ),
    ]
