# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201129_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.PositiveIntegerField(choices=[(1, 'Google Merchant'), (2, 'Синхронизация цен с 1с'), (3, 'Facebook Merchant'), (4, 'Пересчет цен'), (5, 'Синх производителя'), (6, 'Синх цен'), (7, 'XML Export')]),
        ),
    ]
