# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='info@igrushechka.com.ua', max_length=255, verbose_name='Email')),
                ('verified', models.BooleanField(default=0, verbose_name='Email подтвержден')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('lname', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('sname', models.CharField(max_length=255, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='Номер телефона')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False)),
                ('subscription', models.BooleanField(default=True, verbose_name='Подписка на рассылку')),
                ('price_type', models.PositiveIntegerField(choices=[(1, 'Розничная'), (2, 'Биг-оптовая')], default=1, verbose_name='Тип цен')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последний раз на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации')),
                ('device_token', models.CharField(max_length=50, null=True, unique=True)),
                ('notifications', models.BooleanField(default=1)),
                ('fcm_token', models.CharField(max_length=255, null=True)),
                ('update_departaments', models.BooleanField(default=False)),
                ('social_type', models.PositiveIntegerField(choices=[(1, 'fb'), (2, 'g')], null=True)),
                ('social_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PassCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, verbose_name='Код')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
    ]
