BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBB
BBBBB BBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Игрушки') XXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Wader') XXXX
BBBBBBBB